<?php
/**
 * DropCMS Site Configuration — auto-generated by provisioning system.
 */

// ─── Site Identity ──────────────────────────────────────────
define('SITE_URL',   '__SITE_URL__');
define('SITE_NAME',  '__SITE_NAME__');

// ─── Admin Credentials ──────────────────────────────────────
define('ADMIN_USER', '__ADMIN_USER__');
define('ADMIN_PASS', '__ADMIN_PASS__');

// ─── Contact ────────────────────────────────────────────────
define('CONTACT_EMAIL', '__CONTACT_EMAIL__');
define('CONTACT_NAME',  '__SITE_NAME__');
define('CONTACT_BRAND', '__SITE_NAME__');

// ─── CORS Origins ───────────────────────────────────────────
define('CORS_DOMAIN', '__CORS_DOMAIN__');

// ─── Upload Limits ──────────────────────────────────────────
define('MAX_IMAGE_SIZE', 50 * 1024 * 1024); // 50 MB

// ─── Platform (Control Panel) ───────────────────────────────
define('DROPCMS_VERSION', '1.0.0');
define('PLATFORM_REGISTRATION_TOKEN', '__REGISTRATION_TOKEN__');
define('PLATFORM_PANEL_URL', '__PANEL_URL__');
define('PLATFORM_SITE_ID',  '__PLATFORM_SITE_ID__');
define('PLATFORM_API_KEY',  '__PLATFORM_API_KEY__');
